"use strict";
exports.__esModule = true;
//import {cuerpoMedico} from "/.cuerpoMedico";
var cuerpoMedico_1 = require("./cuerpoMedico");
var entrenador_1 = require("./entrenador");
var futbolistas_1 = require("./futbolistas");
var masajista_1 = require("./masajista");
var Seleccion_1 = require("./Seleccion");
var Futbolista1 = new futbolistas_1.futbolista("Lionel", "Messi", "789654", "24/6/1987", "Delantero");
var Futbolista2 = new futbolistas_1.futbolista("Emiliano", "Martinez", "321456", "2/9/1992", "arquero");
var entrenadorSeleccion = new entrenador_1.Entrenador("Lionel ", "Scaloni", "963258", "16/5/1978", 6);
var masajistaSeleccion = new masajista_1.Masajista("Marcelo", "D'Andrea", "456987", "2/9/1969", "masajista");
var CuerpoMedicoSeleccion = new cuerpoMedico_1.cuerpoMedico(masajistaSeleccion, 456223);
var seleccion = new Seleccion_1.Seleccion("Argentina", futbolistas_1.futbolista[], entrenadorSeleccion, masajistaSeleccion);
seleccion.incluirFutbolista(Futbolista1);
seleccion.incluirFutbolista(Futbolista2);
Futbolista1.presentacion();
entrenadorSeleccion.presentacion();
masajistaSeleccion.presentacion();
console.log(Futbolista1);
console.log(Futbolista2);
console.log(entrenadorSeleccion);
console.log(CuerpoMedicoSeleccion);
console.log(seleccion);
